### ISSUE TITLE
Create bindings out of typescript definition files

### ISSUE THREAD

**Issue by flash1293** [jchavarri/rebind#2]
Since there is already a large number of typescript type definitions in the DefinitelyTyped Repo, would it be worth the effort to write a type-"transformator" from typescript to bucklescript/reasonml?

There would definitely (heh) be some trade-offs because typescript types don't fit perfectly to reason types, but it could serve as a nice starting point.

**Comment by jchavarri** [comment]
Thanks for your proposal.

Parsing TypeScript files would certainly require a quite different approach, as the current parser, based on Flow, would not serve in this case.

Looking around, I found https://github.com/andrewray/DefinitelyMaybeTyped, which is written in OCaml and seems to parse TypeScript type definitions.

Maybe this improvement could be something interesting at some point in the future, but i'd like to focus first on the JavaScript story and take it to a stable place, before considering another language. 

What's your use case? Do you want to automate this binding generation to have more bindings to libraries available? Or do you work with TypeScript codebases and want to have an easy way to migrate parts of them to Reason?

**Comment by flash1293** [comment]
DefinitelyMaybeTyped looks like the same idea but for js_of_ocaml. The use case I care about is the automated or semi-automated bucklescript binding generation out of typescript definitions. I imagine porting over 90% of DefinitelyTyped to `bs-*` packages with little manual effort could increase adoption of the reasonml ecosystem for JavaScript/TypeScript-developers.

Maybe I'm mistaken, but typescript definitions look like an easier-to-process "raw material" for bindings than JavaScript samples, which could lead to a higher degree of automation.

But I see your point, maybe this issue is better served as a fork of DefinitelyMaybeTyped targeting bucklescript bindings.

**Comment by jchavarri** [comment]
I totally agree. I 100% see the value, and i'd love to help creating a prototype / proof of concept as a separate repo, if that's something you or someone else would be interested in :)

I also found this other project: https://github.com/fable-compiler/ts2fable that does exactly what you propose but it's written in F#. F# and Reason share a huge % of syntax, so I bet many of the conversions ts2fable is doing could be directly translated into Reason.

**Comment by flash1293** [comment]
Wow, this looks great. I will definitely look into it. I think we can close the issue here and I will open a separate repo.

**Comment by jchavarri** [comment]
Cool! Feel free to @ me in GH or Discord if you want.

I'm also going to cc @rrdelaney here (creator of https://github.com/rrdelaney/ReasonablyTyped) as I know he has spent _a lot_ of time trying to figure out this problem :) And he will definitely know what are the most challenging parts of it.

**Comment by flash1293** [comment]
Oh, I didn't know about ReasonablyTyped - looks pretty far down this road. Maybe it makes more sense to just contribute to that project and help filling in the missing pieces.

@rrdelaney do you think the fs2fable approach makes sense? I don't know whether it's more robust than ReasonablyTyped. A quick smoke test with the jest definitions produced a pretty nice looking F# declaration but failed with ReasonablyTyped (or I may have done something stupid).

**Comment by rrdelaney** [comment]
Hi everyone! Thanks for ccing me 😄 

So ReasonablyTyped is meant to create a Reason binding from any Flow or TypeScript definition. The version last released of ReasonablyTyped (`0.13`) supported TypeScript by first using a library called flowgen to compile that `d.ts` to a Flow definition first, and then compile it to Reason. This was super buggy, and often very lossy. 

In the meantime I've been re-writing the TS integration to natively use TypeScript's parser instead of first compiling through Flow. Here is where most of the source for that is: https://github.com/rrdelaney/ReasonablyTyped/blob/master/src/typescriptBsType.re

@flash1293 I know ReasonablyTyped works fairly well, and can compile ~80% of flow-typed. When working on the TS integration, it's kind of just like hooking up a TS input to the Reason output, in that the code generation doesn't need much work. The part that needs the most work is traversing the TypeScript tree and identifying types. Once that is done, mots codegen should just work.

**Comment by flash1293** [comment]
Thanks a lot for your explanation @rrdelaney. I will try to contribute something to ReasonablyTyped instead of starting some worse additional project - awesome project and great community 👍
